### ISSUE TITLE
1.0.9: cmake dioes not install man pages lvl 3

### ISSUE THREAD

**Issue by kloczek** [google/brotli#832] opened 2020-08-27 14:55 UTC
Just checked 1.0.9 and looks like cmake does not install man devel man pages.

**Comment by eustas** [comment] 2020-08-27 16:06
There are 5 changes to CMakeLists.txt since 1.0.7
Investigating

**Comment by eustas** [comment] 2020-08-27 16:08
v1.0.7 has the same behaviour

**Comment by eustas** [comment] 2020-08-27 16:13
History show it never did.

**Comment by eustas** [comment] 2020-09-21 11:32
Duplicate of #756

**Closed by eustas** 2020-09-21 11:32 UTC
Labels: help wanted
