### ISSUE TITLE
Missing encoder implementation in Java

### ISSUE THREAD

**Issue by guybartal** [google/brotli#938] opened 2021-11-08 08:21 UTC
Hi,

We would like to use both Brotli compression and decompression with Java,
currently, Maven package version 0.1.2 includes only [decompression](https://mvnrepository.com/artifact/org.brotli/dec),
any plans to publish a package for compression?
we've noticed that there's a [Java wrapper code](https://github.com/google/brotli/blob/master/java/org/brotli/wrapper/enc/BrotliOutputStream.java), but it's not part of the [parent](https://mvnrepository.com/artifact/org.brotli/parent/0.1.2) package.

**Comment by hyperxpro** [comment] 2021-11-25 07:51
Try this: https://github.com/hyperxpro/Brotli4j

**Comment by eustas** [comment] 2021-12-15 10:38
Currently we have no resources for pure java encoder... Sorry.
Dupe of #405.
Project Brotli4j looks nice - it builds brotli library for several platforms and loads appropriate library...

**Closed** 2021-12-15 10:39 UTC
